### ISSUE TITLE
Error when trying to train [ZeroDivisionError]

### ISSUE THREAD

**Issue by christophered** [mittagessen/seg#2]
@mittagessen 

```
home@home-lnx:~/seg$ seg train ./data
model output name: model
loading network
/usr/local/lib/python3.6/dist-packages/torchvision/models/squeezenet.py:94: UserWarning: nn.init.kaiming_uniform is now deprecated in favor of nn.init.kaiming_uniform_.
  init.kaiming_uniform(m.weight.data)
/usr/local/lib/python3.6/dist-packages/torchvision/models/squeezenet.py:92: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(m.weight.data, mean=0.0, std=0.01)
calculating class proportions
tensor([nan, nan, nan, nan])
epoch 0  [####################################]  100%
Traceback (most recent call last):
  File "/usr/local/bin/seg", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/home/seg/seg/main.py", line 134, in train
    print("===> epoch {} complete: avg. loss: {:.4f}".format(epoch, epoch_loss / len(train_data_loader)))
ZeroDivisionError: division by zero
```

**Comment by mittagessen** [comment]
That's the userfriendly way of telling you that no ground truth could be found. What exactly is in the `./data` directory?

**Comment by christophered** [comment]
@mittagessen **[`./data`](https://github.com/mittagessen/seg/tree/master/data)** is the folder that you included with **`seg`**.
Later-on, I decided to convert the extension of input images `*.framed.png` to jpg formats, as you suggested in the Training section, an error message appears:
```
(python3) home@home-lnx:~/seg$ seg train ./test
model output name: model
loading network
/usr/local/lib/python3.6/dist-packages/torchvision/models/squeezenet.py:94: UserWarning: nn.init.kaiming_uniform is now deprecated in favor of nn.init.kaiming_uniform_.
  init.kaiming_uniform(m.weight.data)
/usr/local/lib/python3.6/dist-packages/torchvision/models/squeezenet.py:92: UserWarning: nn.init.normal is now deprecated in favor of nn.init.normal_.
  init.normal(m.weight.data, mean=0.0, std=0.01)
calculating class proportions
Traceback (most recent call last):
  File "/usr/local/bin/seg", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/home/seg/seg/main.py", line 110, in train
    weights = train_set.get_target_weights()
  File "/home/home/seg/seg/dataset.py", line 32, in get_target_weights
    target = np.array(target)[:,:,2]
IndexError: too many indices
```
